<?php

use Illuminate\Database\Seeder;

class InformationTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('information')->delete();
        
        \DB::table('information')->insert(array (
            0 => 
            array (
                'id' => 19,
                'location_info' => '111',
                'date' => '2018-02-23',
                'company_name' => '第一工業大学',
                'info' => '第一工業大学の説明',
                'written_test' => '有り',
                'written_test_content' => 'SPI検査',
                'interview' => '学校で行います',
                'industry' => '学校',
                'country' => NULL,
                'recruited_occupation' => '教師',
                'qualification' => 'N1',
                'age_limit' => NULL,
                'grade' => '4年生',
                'graduate' => '無し',
                'condidate' => '無し',
                'job_vote' => '',
                'part_time_job' => '無し',
                'intership' => '不可',
                'created_at' => NULL,
                'updated_at' => '2019-11-27 05:04:44',
                'logo' => '/uploads/images/logo/_1572402766.jpg',
                'url' => 'http://ueno.daiichi-koudai.ac.jp/',
            ),
            1 => 
            array (
                'id' => 20,
                'location_info' => '444',
                'date' => '2016-12-20',
                'company_name' => 'LABI',
                'info' => 'LABIの説明',
                'written_test' => '不明',
                'written_test_content' => 'SPI検査',
                'interview' => '学校で行い',
                'industry' => NULL,
                'country' => '特に無し',
                'recruited_occupation' => '販売',
                'qualification' => 'N2以上',
                'age_limit' => NULL,
                'grade' => '4年生',
                'graduate' => '無し',
                'condidate' => '無し',
                'job_vote' => '',
                'part_time_job' => '有り',
                'intership' => '不可',
                'created_at' => NULL,
                'updated_at' => '2019-11-27 05:05:16',
                'logo' => '/uploads/images/logo/labi_1572403366.jpg',
                'url' => 'http://www.yamadalabi.com/',
            ),
            2 => 
            array (
                'id' => 21,
                'location_info' => '555',
                'date' => '2018-12-20',
                'company_name' => '東芝株式会社',
                'info' => '東芝株式会社の説明',
                'written_test' => '有り',
                'written_test_content' => '不明',
                'interview' => '会社で第一次',
                'industry' => NULL,
                'country' => NULL,
                'recruited_occupation' => 'SE',
                'qualification' => NULL,
                'age_limit' => NULL,
                'grade' => '4年生',
                'graduate' => '無し',
                'condidate' => '無し',
                'job_vote' => '',
                'part_time_job' => '無し',
                'intership' => '相談による',
                'created_at' => NULL,
                'updated_at' => '2019-11-27 05:06:52',
                'logo' => '/uploads/images/logo/_1572403388.png',
                'url' => 'https://www.toshiba.co.jp/',
            ),
            3 => 
            array (
                'id' => 23,
                'location_info' => '777',
                'date' => '2017-06-08',
                'company_name' => 'ドンキホーテ',
                'info' => 'ドンキホーテの説明',
                'written_test' => '不明',
                'written_test_content' => '無し',
                'interview' => NULL,
                'industry' => '営業',
                'country' => '中国',
                'recruited_occupation' => NULL,
                'qualification' => 'N1',
                'age_limit' => '28まで',
                'grade' => '4年生',
                'graduate' => '有り',
                'condidate' => '無し',
                'job_vote' => '',
                'part_time_job' => '有り',
                'intership' => '相談による',
                'created_at' => NULL,
                'updated_at' => '2019-11-27 05:07:36',
                'logo' => '/uploads/images/logo/_1572403572.png',
                'url' => 'https://www.donki.com/',
            ),
            4 => 
            array (
                'id' => 24,
                'location_info' => '333',
                'date' => '2017-01-01',
                'company_name' => 'ビックカメラ',
                'info' => 'ビックカメラの説明',
                'written_test' => '有り',
                'written_test_content' => '無し',
                'interview' => '一次面接　3号館',
                'industry' => '小売業',
                'country' => '中国',
                'recruited_occupation' => 'SE',
                'qualification' => 'N1',
                'age_limit' => '30',
                'grade' => '4年生',
                'graduate' => '有り',
                'condidate' => '有り',
                'job_vote' => '',
                'part_time_job' => '有り',
                'intership' => '有り',
                'created_at' => NULL,
                'updated_at' => '2019-11-27 05:08:09',
                'logo' => '/uploads/images/logo/_1572403591.jpg',
                'url' => 'https://www.biccamera.com/',
            ),
            5 => 
            array (
                'id' => 29,
                'location_info' => '381',
                'date' => '2017-11-07',
                'company_name' => '日建リース',
                'info' => '会社の説明',
                'written_test' => '有り',
                'written_test_content' => '無し',
                'interview' => NULL,
                'industry' => '営業',
                'country' => 'ベトナム',
                'recruited_occupation' => NULL,
                'qualification' => 'N1',
                'age_limit' => '30',
                'grade' => '4年生',
                'graduate' => '有り',
                'condidate' => '無し',
                'job_vote' => '',
                'part_time_job' => '無し',
                'intership' => '可能',
                'created_at' => NULL,
                'updated_at' => '2019-11-27 05:12:03',
                'logo' => '/uploads/images/logo/_1574831523.png',
                'url' => 'https://nikken-lease.co.jp/',
            ),
            6 => 
            array (
                'id' => 30,
                'location_info' => '381',
                'date' => '2017-11-21',
                'company_name' => '株式会社ラピニクス',
                'info' => '会社の説明',
                'written_test' => '有り',
                'written_test_content' => '有り',
                'interview' => '一次面接',
                'industry' => '情報系',
                'country' => NULL,
                'recruited_occupation' => 'SE',
                'qualification' => 'N1',
                'age_limit' => NULL,
                'grade' => '4年生',
                'graduate' => '有り',
                'condidate' => '無し',
                'job_vote' => '',
                'part_time_job' => '無し',
                'intership' => '無し',
                'created_at' => NULL,
                'updated_at' => '2020-01-03 13:10:13',
                'logo' => '/uploads/images/logo/_1578057013.jfif',
                'url' => 'https://www.rapinics.co.jp/',
            ),
            7 => 
            array (
                'id' => 63,
                'location_info' => '381',
                'date' => '2020-10-27',
                'company_name' => 'FTS株式会社',
                'info' => NULL,
                'written_test' => NULL,
                'written_test_content' => NULL,
                'interview' => NULL,
                'industry' => NULL,
                'country' => NULL,
                'recruited_occupation' => NULL,
                'qualification' => NULL,
                'age_limit' => NULL,
                'grade' => NULL,
                'graduate' => NULL,
                'condidate' => NULL,
                'job_vote' => NULL,
                'part_time_job' => NULL,
                'intership' => NULL,
                'created_at' => '2020-01-05 08:19:01',
                'updated_at' => '2020-01-05 13:08:43',
                'logo' => '/uploads/images/logo/fts_1578229723.png',
                'url' => 'https://www.fts.co.jp/',
            ),
            8 => 
            array (
                'id' => 70,
                'location_info' => '255',
                'date' => '2020-07-03',
                'company_name' => 'ヤマト運輸株式会社',
                'info' => NULL,
                'written_test' => NULL,
                'written_test_content' => NULL,
                'interview' => NULL,
                'industry' => NULL,
                'country' => NULL,
                'recruited_occupation' => NULL,
                'qualification' => NULL,
                'age_limit' => NULL,
                'grade' => NULL,
                'graduate' => NULL,
                'condidate' => NULL,
                'job_vote' => NULL,
                'part_time_job' => NULL,
                'intership' => NULL,
                'created_at' => '2020-01-05 12:37:02',
                'updated_at' => '2020-01-05 12:37:02',
                'logo' => '/Template/Gui2019/img/sample.png',
                'url' => NULL,
            ),
        ));
        
        
    }
}